name: Allon Baron
favicon: null
layout_spectrum: 0.40176048898138106
typography_spectrum: 0.7980868075974286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5009361235424876
  lightness: 0.001643576892092824
  saturation: 0.5752399079501629
  rhythmicContrast: 0.32216302840970457
purpose: []
