name: Allon Baron - Shoot-Edit-Story
favicon: null
layout_spectrum: 0.2529511
typography_spectrum: 0.7980868075974286
title: 'Allon Baron - Shoot, Edit and make Film Story'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbdcf0'
    - '#6d738b'
    - '#041310'
    - '#174634'
    - '#0059c5'
  brandStrength: 0.0625
  lightness: 0.001643576892092824
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
